# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b95c5baafcbfb9b3684da4072428e79eb772c94c5c2f9880dbec99e25c0a5310b13d3d47e68167912850b19aaf1412bc2a1294efe79d0858a4fac55e437a9cb2

test:
  secret_key_base: 2c7dcdff2f00a7528ab9aea0dbedd51167737af5adcea653f87aef934526fcbcb87ff192fadca0a4458f37088040f0518807225d14218fbb586dbb5113a6d0e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
